---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: e2e-busybox-deploy-
  namespace: e2e
spec:
  template:
    metadata:
      name: e2e
      labels:
        app: busybox-e2e
    spec:
      serviceAccountName: e2e
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/nfs-e2e:ci
        imagePullPolicy: IfNotPresent
        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: PROVIDER_STORAGE_CLASS
            value: openebs-nfs-rwx

            # Application pvc
          - name: APP_PVC
            value: openebs-busybox

            # Application label
            # Use different 'LABEL' for deployment and statefulset application
          - name: APP_LABEL
            value: 'app=busybox'

            # Application namespace
            # Use different 'namespace' for deployment and statefulset application
          - name: APP_NAMESPACE
            value: app-busybox-ns

            #Persistent Volume storage capacity
          - name: PV_CAPACITY
            value: 5Gi
            
          # Use 'deprovision' for app-clean up
          - name: ACTION
            value: provision

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./e2e-tests/apps/busybox/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
