---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - test_vars.yml

  tasks:
    - block:

          ## Generating the testname for deployment
        - include_tasks: /e2e-tests/utils/create_testname.yml

          ## RECORD START-OF-TEST IN e2e RESULT CR
        - include_tasks: /e2e-tests/utils/update_e2e_result_resource.yml
          vars:
            status: 'SOT'

        - block:
              ## Creating namespaces and making the application for deployment
            - include_tasks: /e2e-tests/utils/k8s/pre_create_app_deploy.yml

            - name: Replace the volume capcity placeholder with provider
              replace:
                path: "{{ application_deployment }}"
                regexp: "teststorage"
                replace: "{{ lookup('env','PV_CAPACITY') }}"

              ## Deploying the application
            - include_tasks: /e2e-tests/utils/k8s/deploy_single_app.yml
              vars:
                check_app_pod: 'yes'
                delay: 10
                retries: 20
          when: "'deprovision' not in action"

        - name: Deprovisioning the Application
          include_tasks: "/e2e-tests/utils/k8s/deprovision_deployment.yml"
          vars:
            app_deployer: "{{ application_deployment }}"
          when: "'deprovision' is in action"

        - name: Setting pass flag
          set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN e2e RESULT CR
        - include_tasks: /e2e-tests/utils/update_e2e_result_resource.yml
          vars:
            status: 'EOT'
